name: Testing
on: Push

jobs:
  my_test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
    - name: Run Django unit test
      run: 
        pip3 install --user django
        python3 manage.py test	
