name: Testing
on: push

jobs:
  my_test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: 
        pip install --user django
        python3 manage.py test	
